### ISSUE TITLE
TypeError: can't pickle cv2.VideoCapture objects

### ISSUE THREAD

**Issue by Saulzar** [MVIG-SJTU/AlphaPose#128]
I know there was another issue which was similar, but I'm also having the same issue.

I'm using opencv from pip,   i.e. pip install opencv_python   
Version 3.4.3.

Have tried several versions from conda, all the same issue
"TypeError: can't pickle cv2.VideoCapture objects"

**Comment by Fang-Haoshu** [comment]
Check the opencv version in your program? Perhaps you are using another version of opencv installed by apt-get.

**Comment by Fang-Haoshu** [comment]
Seems in some PC, it's related with multi-processing problem. Add “--sp” flag and see if it works well. I am still looking for the problem

**Comment by Saulzar** [comment]
It seems --sp is a workaround. Thanks.

Seems to avoid the pickling issue using threads not processes. It's
definitely using the opencv 3.4.3 from pip, I have no other opencv on my
system.

**Comment by Fang-Haoshu** [comment]
Yes, but it might be slower using threads. It would be good to use processes. If you find any solutions,, please let me know:D

**Comment by Utopolis** [comment]
Hi, I have the same problem, @Fang-Haoshu  did you find a solution finally ?

**Comment by josh-bone** [comment]
Having the same issue. Is multi-processing just not supported by cv2?

**Comment by Utopolis** [comment]
After some researchs, it came from the library multiprocess which can't share object very complex  (=doesn't pickable). And a VideoCapture (=a complex class) is not serializable.
I gave up the idea anyway.
I would suggest you, or use the multi porcess (in my case it was impossible, because creating a VideoCapture is a blocking action).
Or create the serialization of the VideoCapture but it is not an easy task... (maybe impossible, don't know)
The option that I chose is to use ffmpeg.
