### ISSUE TITLE
How to use multi-GPUs?

### ISSUE THREAD

**Issue by ro6842** [MVIG-SJTU/AlphaPose#289]
I install AlphaPose in Linux( PyTorch version)
I want to use multi-GPUs, but it doesn't have command like --gpu 0,1,2,3

I tried the command : "CUDA_VISIBLE_DEVICES=0,1,2,3"
But it still runs at GPU 0, using just only single GPU.

I run at 15 seconds 's video, it takes about 3 minutes(Single GPU).
It's too slow. I want to accelerate the efficiency.

How to use multi-GPUs and achieve the 20 fps?
Can somebody help me? Thank you very much!!

**Comment by Fang-Haoshu** [comment]
Hi, using 1080Ti it should achieve 20 fps if there aren't too many people in an image. I will try to add multi-gpu support when I am free. PR is greatly welcomed.

**Comment by ThreeChen** [comment]
we have the same problem.
we turned on --profile and see that a det process may take 0.2s for a image.
And usually it will take about 0.16s in the crop_from_dets function.
I am not sure where really the problem is. Our cpu is a Xeon with 32 threads and the process take all the resources of it. Does it has something to do with the numpy+mkl or some enviroment issues else?

Anyway, in my situation, cpu is the bottleneck. Usually, the gpu has already done its job in "det_loader thread", but the "det_processer" thread is too slow.

Thank you!

**Comment by Fang-Haoshu** [comment]
Hi, how many people are there in an image on average?

**Comment by ThreeChen** [comment]
> Hi, how many people are there in an image on average?

usually, there would be 7. And it seems that the cost is mainly on cv2.warpAffine and 'assign img to zero' in line 258,260,262,264 in img.py

**Comment by gachiemchiep** [comment]
Hi @Fang-Haoshu 
Would you mind upload some of your inference log. That would be great help.

**Comment by JoeyChuuichi** [comment]
faced with the same issue. 

It takes about 3 mins to process a 50-sec video with 30fps with 4 people.
I am using Tesla P100 and specify ```--sp```
I am not sure how ```--sp``` would slow down the processing.
Hopefully, AlphaPose can support multi-GPU and I think it can have a great performance in real time.
