### ISSUE TITLE
Keypoint Ordering

### ISSUE THREAD

**Issue by cocolixiao** [MVIG-SJTU/AlphaPose#302]
文档中有“If the `--format` flag is set to 'cmu' or 'open', the keypoint order is Result for COCO (18 body parts) or Result for MPII (15 body parts)”，但不太清楚具体怎么改？求助各位大佬！！

**Comment by eeric** [comment]
on the 144th line, in fn.py,
>>def vis_frame(frame, im_res, format='coco')
.....
l_pair = [
            (0, 1), (0, 2), (1, 3), (2, 4),  # Head
            (5, 6), (5, 7), (7, 9), (6, 8), (8, 10),
            (17, 11), (17, 12),  # Body
            (11, 13), (12, 14), (13, 15), (14, 16)
        ]

**Comment by cocolixiao** [comment]
@eeric 我试了下，但总是在进度100%后不动了。请问，除此def vis_frame(frame, im_res, format='mpii')还要改动其他吗？

**Comment by YueLiao** [comment]
If using fast inference, you may first replace out.narrow(1, 16, 17） with out.narrow(1, 0, 17) on line 68 in main_fast_inference.py. The first 17 channels of out are for coco, other 16 for mpii, but some hard code limits the channel size of out keypoint prediction must be 17.   Then, on line 184 and line 185 in fn.py, you should remove the first channel, just like: 
        kp_preds = human['keypoints'][1:,:]
        kp_scores = human['kp_score'][1:]
and remove line 186 and 187, which is for coco.

**Comment by surelyee** [comment]
@YueLiao  hi~, if i use out.narrow(1, 17, 16) , this way can straightly get 16 mpii channel?

**Comment by surelyee** [comment]
@YueLiao  if you have finish it, i want to ask some questions.
do you use the result to test mAP with crowdpose_val.json?  my result maybe is wrong

**Comment by YueLiao** [comment]
@surelyee Hi~, you cannot directly use out.narrow(1, 17, 16) to get MPII result, because some operations are required the result must 17 channels. You should firstly use out.narrow(1, 16, 17), then remove the first channel.

**Comment by surelyee** [comment]
@YueLiao  hi~,thanks, i change all operations of the number 17 became 16, maybe i was wrong , i want to ask you some questions.
my result follows:
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.702
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.860
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.756
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.777
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.925
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.824
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=  easy | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.432
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=  hard | maxDets= 20 ] = -1.000

author's result and paper's result :
Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.660
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.842
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.715
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.727
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.895
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.775
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=  easy | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.411
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=  hard | maxDets= 20 ] = -1.000

maybe i was wrong , but i don't know, my result is higher than author's result. maybe author didn't use mpii channel to get the result.
can you let me know your result using mpii? thanks

**Comment by YueLiao** [comment]
@surelyee I haven't conducted an evaluation on MPII dataset, but the result reported in Alpha pose is 82.1. The result in RMPE is an older version, which has been improved in this project. Maybe you can test with mode " --fast_inference False " to get the more accurate result.

**Comment by surelyee** [comment]
@YueLiao thanks, i use the same data sets with author (crowdpose), and use the same crowdpose_val.json to test. but author's result is  66.0 in crowdpose paper and i get 70.2 result. so i don't know the reason.
thanks.

**Comment by FightStone** [comment]
@surelyee @YueLiao Hello！
I trained the model on the coco train, tested it on the crowdpose val dataset, and i removed the first 15 of the keypoints in the output json (because crowdpose does not have noses, left and right eyes, and left and right ears), and fill in six 0s behind (Crowdpose has a head and a neck). 
At the same time, the last six digits (head and neck) of crowdpose json are changed to 0, because coco does not detect the head and neck. But the output is as follows:

Average Precision  (AP) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.808
 Average Precision  (AP) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.955
 Average Precision  (AP) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.870
 Average Recall     (AR) @[ IoU=0.50:0.95 | area=   all | maxDets= 20 ] = 0.850
 Average Recall     (AR) @[ IoU=0.50      | area=   all | maxDets= 20 ] = 0.961
 Average Recall     (AR) @[ IoU=0.75      | area=   all | maxDets= 20 ] = 0.899
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=  easy | maxDets= 20 ] = -1.000
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=medium | maxDets= 20 ] = 0.790
 Average Precision  (AP) @[ IoU=0.50:0.95 | area=  hard | maxDets= 20 ] = -1.000

maybe i was wrong , but i don't know, my result is higher than author's result (although I did not test the head and neck). Looking forward to your reply. Thank you.
