### ISSUE TITLE
Speed difference on 1060 6GB and Tesla V100 16GB

### ISSUE THREAD

**Issue by teaddicted** [MVIG-SJTU/AlphaPose#313]
Hey,

I'm getting much less speed on AWS instance (Tesla V100 16GB --- 8 Cores) than on my laptop (1060 6GB --- 4 Cores). 
The speed difference is almost 2x. A 1 minute video takes about 3 minutes to process on my laptop, however the same video takes about 5-6 minutes to process on AWS instance. 

I've tried updating GPU drivers, also tried speeding-up-alphapose changes but results are not being improved. Is this what I should expect with the instance?

Can you please tell me what I can do to achieve better results on the instance considering its GPU is much better than my laptop's. 

Thanks.

**Comment by aGoodLearner** [comment]
Do you run it on the server?

**Comment by teaddicted** [comment]
Yes. But the speed is really slow even with multi-gpu.

**Comment by aGoodLearner** [comment]
> Yes. But the speed is really slow even with multi-gpu.

I also meet this problem in server , but in my PC(Inter Core i5, 16G, GTX1070, Python3.6, TOuch0.4.0) it workd very well .I solve this problem in this way , Maybe it is due to touch,  This is a function in touch named from_numpy which in preprocess.py, i test it can use full cpu, No matter how many cpus your computer has, it can cause you cpu to 100%, i set the touch number thread ( torch.set_num_threads(3) ) before use it, and set more in after thread, it seems to work, I am Chinese, My English is poor, I don't know if I made myself understood

**Comment by aGoodLearner** [comment]
Torch , I write it in Touch
