### ISSUE TITLE
How to get the output image.

### ISSUE THREAD

**Issue by Yellow-Champagne** [MVIG-SJTU/AlphaPose#360]
I use this command"python demo.py --indir examples/demo --outdir examples/res --vis --save_img --sp" to get the output image.But there is no image in the  examples/res,only JSON file.What shuold I do?

**Comment by Danelljian** [comment]
you can debug the scripts,save image in the Class DadaWriter of dataloder.py. you will find it

**Comment by learnermaxRL** [comment]
vis_frame is the function they use.Checkout that function  and you will get the idea.

**Comment by GuoHaiYang123** [comment]
If you process only one image at a time ,the code maybe make mistake like  no processed image in the examples/res/vis,only JSON file,but if you process several images at a time,it will work.I know this tip because I have faced the same issue.

**Comment by Fang-Haoshu** [comment]
A possible problem is that there are no person detected in that image

**Comment by stefanochiocca** [comment]
I'm having the same issue, I can run without errors the demo.py and I'm pretty sure that there are people in the images and they are detected because the json file isn't empty. but even if **--save_img** is turned on I can't visualize the results in /vis dir. I'm running the framework on windows 10. any help?
