### ISSUE TITLE
Can I use camera as input?

### ISSUE THREAD

**Issue by job2003** [MVIG-SJTU/AlphaPose#39]
您好，目前给的例子只是用了图片或者视频流作为输入，是否支持实时采集摄像头数据，然后进行处理呢？谢谢！

**Comment by YuliangXiu** [comment]
Sorry, we did not provide camera input support because current estimator cannot achieve real-time inference performance. If you want to use a camera stream as input, you can refer to MobilePose-PyTorch's [estimator.py](https://github.com/YuliangXiu/MobilePose-pytorch/blob/master/estimator.py) and [run_webcam.py](https://github.com/YuliangXiu/MobilePose-pytorch/blob/master/run_webcam.py). I wrote some codes on reading camera stream and rendering estimated poses results. Hope it will help you.

**Comment by wiwengweng** [comment]
can't wait to see ur wonderful piece~! 👍

**Comment by Fang-Haoshu** [comment]
Oh yeah, for the pytorch version, it's coming!

**Comment by wiwengweng** [comment]
I see the beta version, but still exciting to wait the camera version. As you know openpose is working on camera already. Big challenge, yea? 💯
