### ISSUE TITLE
About joint jitter

### ISSUE THREAD

**Issue by murdockhou** [MVIG-SJTU/AlphaPose#409]
Hi, thanks for your work. I have some question about STN network effection in your original paper. I have found that most of human pose-estimation network when runs on a video, the joints of same person jitter is more serious. Is the STN network can reduce joint jitter appearance? And if so, could you please give me more instructions about the STN & STDN network since i can not make sense the stn layer in [this](https://github.com/MVIG-SJTU/RMPE/blob/master/src/caffe/layers/st_layer.cpp).

**Comment by Fang-Haoshu** [comment]
Hi, we believe that the joint jittering is brought by training data since the pixel-level location of the joint can vary for different persons. Even for a human, if we annotate each frame independently, the results can also look like jittering. Thus, a better solution might be using time smoothing. 

Best
