### ISSUE TITLE
'EasyDict' object has no attribute 'DATA_PRESET' ？？about cfg_file

### ISSUE THREAD

**Issue by zjzhengyin** [MVIG-SJTU/AlphaPose#541]
After solving many problems, my parameter input is as follows: 
Python scripts/demo_inference.py --cfg 1.yaml --checkpoint 1.pth --video D: \ 1.avi --outdir examples / res --save_video
But the attribute error: 'Easy dict' object has no attribute 'data' preset 'appears. 
I'm confused about it

**Comment by jpbranson** [comment]
This was also happening to me. What .yaml file are you using for --cfg? Is it from the [MODEL_ZOO](https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md)?

**Comment by Fang-Haoshu** [comment]
Hi, what .yaml file are you using

**Comment by jpbranson** [comment]
@Fang-Haoshu I'm not the original poster, but I struggled in understanding the `--cfg` tag when first trying to use it. I thought because the tag was "--cfg" I was supposed to use a ".cfg" file from `/detector/yolo/cfg`. The error stumped me for a long time until eventually I tried using the appropriate `.yaml` file from `MODEL_ZOO`.

I am not experienced at this however, so please disregard if it should have been apparent

**Comment by Fang-Haoshu** [comment]
Oh I see, sorry for the confusion. I update an example in the readme. 

Best wishes
