### ISSUE TITLE
provide pretrained model of Halpe dataset (136 keypoints) 

### ISSUE THREAD

**Issue by liangshi036** [MVIG-SJTU/AlphaPose#700]
pretrained model of Halpe dataset (136 keypoints) URL(google or baidu) is empty，would you please update the URL in MOODLE_ZOO.md ? 

thank you for your attention.

**Comment by ludiccc** [comment]
Hi!

I second this request.

Thanks and great work!

**Comment by nikhilweee** [comment]
This should help: https://github.com/MVIG-SJTU/AlphaPose/issues/695#issuecomment-695879500

**Comment by bshreyas13** [comment]
Hey guys I am trying to train on Halpe_136 from scratch, and it crashes when it starts training and tries to pull the img_id in custom.py.. I have extracted the images in DATA1/Benchmark/... as per the path in the script..
My annotations file is in data/halpe_136/annotations and I have pointed to this path in the config file.

I am not sure my it's getting a dict for img_path instead of the path to the image. Any inputs on setting up halpe_136 and training it would help. I will be more than happy to share the pre-trained model if I can get it working.

Thanks

**Comment by Fang-Haoshu** [comment]
Hi, sorry for the confusion. I updated the code and models.
You can pull the latest code and download the new models in MODEL ZOO: https://github.com/MVIG-SJTU/AlphaPose/blob/master/docs/MODEL_ZOO.md

Script for running is also available.
