### ISSUE TITLE
直接训练coco数据集只达到了mAp 0.69

### ISSUE THREAD

**Issue by lawo123** [MVIG-SJTU/AlphaPose#934]
![image](https://user-images.githubusercontent.com/44777088/137240375-bbe42ef4-6d5b-40ff-a3fc-dacced95db46.png)
您好，按照您的代码训练fastpose在coco数据集上的结果，##### Epoch 199 | gt mAP: 0.7252916811102725 | rcnn mAP: 0.6978454378890657 #####，没有复现出您mAP 0.72的结果呢

**Comment by lawo123** [comment]
> ![image](https://user-images.githubusercontent.com/44777088/137240375-bbe42ef4-6d5b-40ff-a3fc-dacced95db46.png) 您好，按照您的代码训练fastpose在coco数据集上的结果，##### Epoch 199 | gt mAP: 0.7252916811102725 | rcnn mAP: 0.6978454378890657 #####，没有复现出您mAP 0.72的结果呢

**Comment by lawo123** [comment]
> ![image](https://user-images.githubusercontent.com/44777088/137240375-bbe42ef4-6d5b-40ff-a3fc-dacced95db46.png) 您好，按照您的代码训练fastpose在coco数据集上的结果，##### Epoch 199 | gt mAP: 0.7252916811102725 | rcnn mAP: 0.6978454378890657 #####，没有复现出您mAP 0.72的结果呢



> ![image](https://user-images.githubusercontent.com/44777088/137240375-bbe42ef4-6d5b-40ff-a3fc-dacced95db46.png) 您好，按照您的代码训练fastpose在coco数据集上的结果，##### Epoch 199 | gt mAP: 0.7252916811102725 | rcnn mAP: 0.6978454378890657 #####，没有复现出您mAP 0.72的结果呢

**Comment by lawo123** [comment]
> 梯度下降不是看运气的吗😂

相同的代码，如果初始化参数和随机种子设的一样，那结果不应该完全一样吗？

**Comment by GitHubjinliu** [comment]
请问您最终复现的结果是多少呀？

**Comment by hongyaohongyao** [comment]
> 请问您最终复现的结果是多少呀？我是用给的预训练模型，跑了1000张验证及图片，计算rcnn只有 mAP 12.1

我自己轻量化了网络结构，结果大概map大概60多

**Comment by GitHubjinliu** [comment]
谢谢回复！同时想请教一个问题：不同的检测器（例：yolov3、yolov5），训练的模型会有区别吗？或者说：检测器对训练过程有影响吗？因为我发现只是在计算rcnn_mAP时才会用检测器生成一个det_yolo.json。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MVIG-SJTU/AlphaPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 晚上9:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934)





  
请问您最终复现的结果是多少呀？我是用给的预训练模型，跑了1000张验证及图片，计算rcnn只有 mAP 12.1
  
我自己轻量化了网络结构，结果大概map大概60多
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by hongyaohongyao** [comment]
> 谢谢回复！同时想请教一个问题：不同的检测器（例：yolov3、yolov5），训练的模型会有区别吗？或者说：检测器对训练过程有影响吗？因为我发现只是在计算rcnn_mAP时才会用检测器生成一个det_yolo.json。
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MVIG-SJTU/AlphaPose" ***@***.***&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:10 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934) 请问您最终复现的结果是多少呀？我是用给的预训练模型，跑了1000张验证及图片，计算rcnn只有 mAP 12.1 我自己轻量化了网络结构，结果大概map大概60多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

影响应该不是很大

**Comment by GitHubjinliu** [comment]
谢谢！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MVIG-SJTU/AlphaPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934)





  
谢谢回复！同时想请教一个问题：不同的检测器（例：yolov3、yolov5），训练的模型会有区别吗？或者说：检测器对训练过程有影响吗？因为我发现只是在计算rcnn_mAP时才会用检测器生成一个det_yolo.json。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MVIG-SJTU/AlphaPose" @.&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:10 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934) 请问您最终复现的结果是多少呀？我是用给的预训练模型，跑了1000张验证及图片，计算rcnn只有 mAP 12.1 我自己轻量化了网络结构，结果大概map大概60多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
影响应该不是很大
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by GitHubjinliu** [comment]
您是用的哪个检测器训练的？yolov3 or yolov3-spp？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "MVIG-SJTU/AlphaPose"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月4日(星期四) 晚上9:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934)





  
谢谢回复！同时想请教一个问题：不同的检测器（例：yolov3、yolov5），训练的模型会有区别吗？或者说：检测器对训练过程有影响吗？因为我发现只是在计算rcnn_mAP时才会用检测器生成一个det_yolo.json。
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MVIG-SJTU/AlphaPose" @.&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:10 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934) 请问您最终复现的结果是多少呀？我是用给的预训练模型，跑了1000张验证及图片，计算rcnn只有 mAP 12.1 我自己轻量化了网络结构，结果大概map大概60多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
影响应该不是很大
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by thisimyusername** [comment]
> 谢谢！
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MVIG-SJTU/AlphaPose" ***@***.***&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:16 ***@***.***&gt;; ***@***.******@***.***&gt;; 主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934) 谢谢回复！同时想请教一个问题：不同的检测器（例：yolov3、yolov5），训练的模型会有区别吗？或者说：检测器对训练过程有影响吗？因为我发现只是在计算rcnn_mAP时才会用检测器生成一个det_yolo.json。 … ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "MVIG-SJTU/AlphaPose" @.&gt;; 发送时间:&nbsp;2021年11月4日(星期四) 晚上9:10 @.&gt;; @.@.&gt;; 主题:&nbsp;Re: [MVIG-SJTU/AlphaPose] 直接训练coco数据集只达到了mAp 0.69 (#934) 请问您最终复现的结果是多少呀？我是用给的预训练模型，跑了1000张验证及图片，计算rcnn只有 mAP 12.1 我自己轻量化了网络结构，结果大概map大概60多 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android. 影响应该不是很大 — You are receiving this because you commented. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
您好 ，看到您的问题 我也有类似问题想和您交流。我在训练模型的时候输出了##### Epoch 6 | gt mAP: 0.5692155397053213 | rcnn mAP: 0.5541170346811128 #####， 运行validate.py输出
![image](https://user-images.githubusercontent.com/38216798/148672185-9236a2ec-018a-44a3-9184-0d649c816d4d.png)，，这四个不同的指标gt mAP, rcnn mAP, gt box mAP, det box mAP哪个才能看出关键点预测的准确度。我修改了检测模型后再运行validate.py测试 发现只有det box发生了变化，gt box没变。按理说 这种top-down的姿态估计的结果受检测器影响较大。我不清楚是不是我对这些指标理解有误。关于这些指标的意思 您能否提供一些思路？

**Comment by thisimyusername** [comment]
> ![image](https://user-images.githubusercontent.com/44777088/137240375-bbe42ef4-6d5b-40ff-a3fc-dacced95db46.png) 您好，按照您的代码训练fastpose在coco数据集上的结果，##### Epoch 199 | gt mAP: 0.7252916811102725 | rcnn mAP: 0.6978454378890657 #####，没有复现出您mAP 0.72的结果呢 @Fang-Haoshu

您好 请教您一个问题 ，训练过程输出的gt mAP和rcnn mAP哪个是您提到的mAP呢？作者提供的结果
![image](https://user-images.githubusercontent.com/38216798/148672492-5777b44a-5da5-4349-845f-165ae3c50992.png)
 AP是通过这两个值计算得到的吗？

**Comment by wangrunzhi991212** [comment]
同问，官方给出的Fast Pose 的AP是72.0，我去查看了training log 里面输出的 gt mAP 和 rcnn mAP 都不符合这个72.0，想请问一下这个表格中给出的AP到底是指的什么呢？以及对应在代码哪个位置计算出来的呢
