### ISSUE TITLE
Real-time pytorch release date?

### ISSUE THREAD

**Issue by fire17** [MVIG-SJTU/AlphaPose#98]
Hey guys,
for a while now I've seen the fps listed on the pytorch branch go from 5 to 15 to 15-20 fps. It's says that in 2 days we will get a stable real-time version for about a week... Any update you can give on how soon this will be released? Thank you very much! :)

**Comment by Fang-Haoshu** [comment]
Hi, in fact the "real-time" is pretty hard to define, some would regard 10 fps as real-time while others may think it should be 25 fps. We are working to achieve a final speed of 25 fps and are almost there.  Hopefully, I will make a release in a week. Currently, I am doing some test to make sure that there are no bugs. Sorry for the delay since we are out of human resources...

**Comment by vtyw** [comment]
Hello. Did this release ever happen? What is currently meant to be faster, the pytorch branch or using run.sh? (I have gotten the pytorch version running but it is quite slow for videos.)
